### ISSUE TITLE
Request for clarification on complex text shaping

### ISSUE THREAD

**Issue by progers** [w3c/svgwg#65] opened 2016-03-10 22:52 UTC
Gecko positions text in individual characters but renders combined glyphs (typographic character units[1]) which matches the spec. Blink and WebKit position and render individual character glyphs, in violation of the spec. I started updating Blink's SVG text layout to use HarfBuzz's complex text shaping and match the spec, but I think it would be a regression for our users.

Consider the following examples in Gecko vs Blink:
"traffic" vs "transit" with rotation: http://output.jsbin.com/xajice
"traffic" vs "transit" on a curve: http://output.jsbin.com/haqaxi
"yeah!" with diacritics: http://output.jsbin.com/gefuca

These examples look best in OSX10.11.3. Because shaping depends on platform-specific fonts, the examples change based on your OS (using "serif" instead of "cursive" on ubuntu demonstrates some of these issues). This fact seems like very surprising behavior for authors, particularly if the content is dynamic.

I don't have an idea of how to make this better but my wishlist includes:
1) Replacing "traffic" with "transit" does not wildly change text rendering.
2) Arabic is not a second-class citizen in SVG, even with word ligatures [2].

[1] https://drafts.csswg.org/css-text-3/#typographic-character-unit
[2] https://en.wikipedia.org/wiki/Arabic_script_in_Unicode#Word_ligatures

**Comment by progers** [comment] 2016-03-30 04:28
@heycam, do you have thoughts on this? The issue we're hitting is that the new typographic character unit spec text is not compatible with SVG's existing character-based APIs in common scenarios (ligatures, diacritics, and heavily-shaped text such as Arabic).

I've uploaded a comparison of each browser on the above testcases:
https://pr.gg/characterPositioningComparison.png

**Comment by Tavmjong** [comment] 2016-03-30 08:53
I think that rotating glyphs, placing them on a path (when the 'method' attribute value 'align'), etc. should break discretionary ligatures much as a non-default value for 'letter-spacing' see: https://www.w3.org/TR/css-text-3/#letter-spacing-property ). I can make this clear in the SVG 2 spec.

As for mandatory ligatures (as with Arabic) on a path, the only real solution is to implement the <textPath> 'method' attribute value 'stretch': See: https://svgwg.org/svg2-draft/text.html#TextPathElementMethodAttribute

I looked at text-on-a-path rendering issues a number of years ago. See: http://tavmjong.free.fr/SVG/TEXT_PATH/TextPath.html

**Comment by fsoder** [comment] 2016-03-30 09:44
I think that sounds reasonable, and likely to match most expectations (@progers wishlist point 1). Let's hope it's possible to squeeze into the new spec text without too much trouble... There's still the question of what things like getExtentOfChar - for say the middle 'f' in 'ffi' - should return in the different contexts though.

I guess it does require implementers to "know" the reason for a typographic character unit (I suspect we'd want to shape as few times a possible...)

**Comment by progers** [comment] 2016-03-31 00:46
Thanks @Tavmjong, I think breaking discretionary ligatures by default would help quite a bit when using rotate, text-on-a-path, etc. Can we specify exactly what should happen for mandatory ligatures too (for both rotate/dx/etc and text-on-a-path)?

There's still an issue of combining characters (the "y[hat]eah!" example) with rotate/dx/etc. Using typographic character units for rotate/dx/etc seems like it would be the most intuitive behavior.

@fsoder, I think the updated spec text for getExtentOfChar is to return the extent of the full 'ffi' for the middle 'f'. The spec needs to be updated to use "typographic character unit" instead of "grapheme cluster" though.

**Comment by Tavmjong** [comment] 2016-04-05 15:58
I'm having second thoughts about changing the default behavior in the SVG spec for text on a path with discretionary ligatures. If the 'method' is 'stretch' then you would normally want to keep discretionary ligatures as you also might want to do if the curvature is small. So for consistency (and backwards compatibility with SVG 1.1) I think the behavior should stay the same. SVG 2 does require support for the 'font-variant-ligatures' property which can disable discretionary ligatures when they result in poor quality rendering.

As for mandatory ligatures, isn't the SVG specification clear enough? What is missing? For high quality results, the 'method' value 'stretch' should be used. (I don't think it is very hard to implement.)

Using the typographic character unit does seem to make sense. It would be good to have someone with more experience to comment on if there are any backwards compatibility issues.

I'm hoping @heycam will add his comments.

**Comment by progers** [comment] 2016-04-05 20:24
@Tavmjong, because ligatures depend on the fonts available on a specific platform, are we okay with a default behavior that differs depending on your OS? In other words, font-variant-ligatures lets us control ligatures, but what is the default value for text on a path or dx, rotate, etc? There is essentially no compatibility in existing implementations so I'm less concerned with breaking backwards compatibility.

Can you describe what the examples should look like in SVG 1.1 and SVG 2?

**Comment by AmeliaBR** [comment] 2016-04-05 22:44
I think I agree with Tav's [most recent comment](https://github.com/w3c/svgwg/issues/65#issuecomment-205869481) regarding ligatures & text-on-a-path: keep the current spec, but allow authors to control with `font-variant-ligatures`.

Regarding the other issues, I see two features that are not clearly defined in the spec:

- the impact of `rotate`.  I would recommend adding it in (with letter-spacing) as an effect that should break discretionary ligatures.
- which types of `textLength` adjustments should count as non-default letter-spacing for the same requirement.  I would recommend that `spacing` adjustments break discretionary ligatures, but `spacingAndGlyphs` adjustments don't.

The non-normative prose with respect to `spacing` and `textLength` should also be changed to refer to _n_ **glyphs** instead of _n_ **characters**.

The impact of `dx` is defined: the glyph is placed at the first position, and then any subsequent deltas are summed together to get the net offset for the next independent character.  It should perhaps be clarified that this applies to combining diacritics as well as to ligatures.

As far as the JSBin examples, what are the differences you're seeing between Gecko and Blink, @progers ? On Windows, I'm not seeing any discretionary ligatures getting applied with the default cursive font (Comic Sans).  Therefore, the only browser differences I'm seeing are for the combining diacritic, and I don't like either version: Blink spaces out the accent as a separate character, Gecko draws the combined glyph properly, but then adds double spacing before the next glyph.  Which is a literal interpretation of the current spec, but would be fixed by the character/glyph change.

**Comment by progers** [comment] 2016-04-05 22:47
@AmeliaBR, thanks for the detailed response. https://pr.gg/characterPositioningComparison.png is how the jsbin examples look on OSX.

**Comment by AmeliaBR** [comment] 2016-04-05 23:14
Thanks for the screenshots Philip,

For text on a path, the Firefox implementation would be the correct one, even if it is not so elegant in this case.  That's assuming the _ffi_ ligature is classified as a "common ligature" (`clig`) in the font, and is therefore one of the features [that is supposed to be on by default](https://drafts.csswg.org/css-fonts/#default-features).  Note that Blink & WebKit are not applying the ligature even in regular SVG text (as demonstrated by the independent rectangles for each character) -- or if that is the ligature, then the `getExtentOfChar` results do not conform to the spec (should be the extent of the glyph of which that character is part).

For the rotated text, as I pointed out, the current spec is not clear (e.g., does this count as "when the spacing between two characters is not the same as the default space"), but I would lean towards clarifying it such a way that the Blink & WebKit implementation are correct & Firefox is wrong.

For the combining diacritics, my comments from Windows are applicable here, too.  In addition, something weird is going on with the `getExtentOfChar` boxes in Chrome, that is inconsistent across operating systems: your screenshot shows half-width boxes for both characters, I'm getting a regular box for the y and a zero-width box for the accent.

As an aside: we use the terms "discretionary ligatures" and "required ligatures" somewhat loosely in the spec.  We should clearly define that to indicate which OpenType features fall into each class.

**Comment by Tavmjong** [comment] 2016-04-06 13:16
Blink on Linux does appear to be applying "common" ligatures in SVG (it even won't allow you to turn them off!). It appears getExtendOfChar is returning the width divided by the number of characters in the glyph. This is actually more useful. We have a patch somewhere that does this in Inkscape and it makes editing text much easier as then, for example, you could select the 'f' in the middle of 'ffi' and delete it (not so valuable for this case but quite valuable when editing, for example, South Asian languages).

"Not the same as default spacing" means if you use the 'letter-spacing' property or there is a change due to justification (see: https://www.w3.org/TR/css-text-3/#letter-spacing-property). Using 'textLength' as a means of justification probably should not follow this rule as the attribute is intended for minor corrections to ensure that the author's measure of text length is the same as rendered  (not the kind of use one sees in the example here). Imagine that you are an author using this property for the intended reason. You would not expect ligatures to be broken, especially if the rendered text width matches the author's calculated width (or is off by only a tiny amount).

Note that letter spacing ignores zero width characters (see same reference as above). I assume this would include combining diacritics. It would then make sense to treat them and the glyph they combined with as a typographical character unit and space/rotate them together.

I've added a list of which OpenType features are "discretionary" and which are "required" to the SVG 2 spec.

**Comment by AmeliaBR** [comment] 2016-04-06 18:00
Thanks Tav,

Do you agree that `rotate` (with a value other than 0 for either of adjacent characters) should also trigger the "not the same as default spacing" behavior?

I agree with you on `textLength` and not wanting to trigger a change to text-shaping for minor adjustments when the  attribute is used as intended.  If someone wants to abuse the feature to create letter-spacing, they can also manually turn off common ligatures.

For `getExtentOfChar`, you make a good point of usefulness, but this would mean a breaking change to the spec.  However, if browsers are currently inconsistent about this aspect anyway, that's probably acceptable.  We'd need a proper resolution.  Can you put together a proposed wording?

**Comment by Tavmjong** [comment] 2016-04-06 18:41
I have a slight preference that rotate not trigger the same default spacing behavior (for consistency with the model of how CSS text gets laid out first and then 'dx', 'dy', and 'rotate' are applied afterwards). But I could be convinced otherwise. Again, Cameron's input would be appreciated.

**Comment by AmeliaBR** [comment] 2016-04-06 21:19
Shouldn't `dx` per-character values (other than 0, or `dy` for vertical text) have the same effect?  It's not a separate "text chunk" for alignment purposes, but it is non-default character spacing.  So you'd already be flagging the text for special shaping behavior.

**Comment by heycam** [comment] 2016-04-07 05:21
Sorry for not replying earlier. I would love it if we could define any automatic turning off of discretionary ligatures as due to changes to 'font-variant-ligatures', and I would like to avoid poking ligature-requirements from the SVG layer down into the CSS layer, if possible.

For textPath, we could do this with a UA style sheet rule:

```
textPath { font-variant-ligatures: none; }
```

That would ensure that "traffic" (assuming a sensible font) will look nicer, and Arabic reads correctly (but doesn't look as nice).  `method="stretch"` is the right solution there, I think.  This approach would mean that with `method="stretch"` you wouldn't get the ligatures that come with font-variant-ligatures:normal, but authors would still be able to opt in to them.

So I think we should do something like this. Firefox is an outlier here, it's a regression and there have been bug reports I think. (It fell out of our SVG text rewrite a few years ago.)

Even if we don't use a UA style rule, prose that does the equivalent (just like the prose for 'letter-spacing' does) would be OK with me.

I think a difficulty with disabling discretionary ligatures in the presence of `rotate=""` values is that they don't correspond to entire elements, and so internally we can't handle it the same way as  'font-variant-ligatures' on an individual element. This also feels like a violation between the CSS and SVG text layout layers, so if we can avoid it I would prefer to. (I don't recall getting bug reports about `rotate=""` applying to entire glyphs when there are ligatures.)

**Comment by heycam** [comment] 2016-04-07 05:24
Oh, `textLength="..." lengthAdjust="spacing"` disabling discretionary ligatures in a similar way would be fine with me.  I suppose that means prose, although you could write:

```
text[lengthAdjust=spacing],
text[lengthAdjust=spacing] { font-variant-ligatures: none; }
```

it feels a bit more fragile, given it wouldn't work with white space in the attribute value, or different casing, etc.

**Comment by AmeliaBR** [comment] 2016-06-10 20:17
Resolutions from [9 June 2016 telecon](https://www.w3.org/2016/06/09-svg-minutes.html#resolution02):

- **We will keep SVG 1.1 behaviour wrt to ligatures allowed on text on a path.**  Authors can use font features properties (which are mandatory for SVG 2 conformance) if discretionary ligatures are inappropriate.
- **lengthAdjust=spacing will not break ligatures. Ligatures must be explicitly broken** [by font feature properties].

We didn't record a separate resolution, but we agreed the same for `rotate`: keep the SVG 1.1 behavior, where entire ligature glyphs can be rotated.

This ensures that ligatures will work as normal in cases where they aren't a problem (i.e., minor text length adjustments or text on a path with subtle curvature or stretch mode), but still allows authors control to prevent unattractive examples like those @PRogers gave.  It also means that implementers can handle text shaping & ligature formation in a CSS-compatible manner, and then apply the SVG-specific text layout properties to the result on a glyph-by-glyph basis.

**Comment by Tavmjong** [comment] 2016-06-19 09:20
Updated text in commit 6ffc0edca7305e69068f071182f624835c2b94b1

**Closed by Tavmjong** 2016-06-19 09:20 UTC
Labels: London 2016, New, SVG 2, Text chapter
