### ISSUE TITLE
SVGAElement has a clashing definition of href

### ISSUE THREAD

**Issue by lukebjerring** [w3c/svgwg#709] opened 2019-07-04 16:05 UTC
From https://svgwg.org/svg2-draft/linking.html#InterfaceSVGAElement

    SVGAElement includes SVGURIReference;
    SVGAElement includes HTMLHyperlinkElementUtils;

Which have definitions

    [SameObject] readonly attribute SVGAnimatedString href;

and 

    [CEReactions] stringifier attribute USVString href;

respectively.

This is being picked up in https://github.com/web-platform-tests/wpt/pull/12231 which is attempting to test for clashing member definitions.

**Comment by AmeliaBR** [comment] 2019-07-04 17:08
Duplicate of #312. The backwards-compatible requirement is to have the SVG version take precedence, but yes, we know the IDL is broken. Any suggestions for fixes welcome (comment on #312).

**Closed by AmeliaBR** 2019-07-04 17:08 UTC
