### ISSUE TITLE
"mode" of a shadow root which <use> element uses is unclear

### ISSUE THREAD

**Issue by hayatoito** [w3c/svgwg#396] opened 2018-03-28 04:50 UTC
The spec says `<use>` element uses a shadow root.
https://svgwg.org/svg2-draft/struct.html#UseShadowTree

However, I guess, this part was written at the era of Shadow DOM v0, which is now dead.
Shadow Root in Shadow DOM v1 has [mode](https://dom.spec.whatwg.org/#shadowroot-mode), which changes the behavior of a shadow root.

It would be better to clarify which shadow root, `open` or `closed`, `<use>` elements use. That is observable.

The relevant discussion in chromium is
https://chromium-review.googlesource.com/c/chromium/src/+/981817

**Comment by hayatoito** [comment] 2018-03-28 04:54
It looks the space says:

> The shadow tree is open (inspectable by script), but read-only. Any attempt to directly modify the elements, attributes, and other nodes in the shadow tree must throw a NoModificationAllowedError.

That sounds `closed` mode to me. I think we can remove this paragraph if the spec can use Shadow DOM v1's terminology.

**Comment by AmeliaBR** [comment] 2018-04-02 19:25
Closing as a duplicate of #363. I think the discussion there is definitely in favor of making the shadow tree closed, but if you have any other suggestions on cleaning up the interfaces to be more consistent with the rest of Shadow DOM, we'd appreciate your input, @hayatoito!

**Closed by AmeliaBR** 2018-04-02 19:25 UTC
