### ISSUE TITLE
stroke-width initial value must include units

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/svgwg#529] opened 2018-08-17 14:14 UTC
At https://svgwg.org/svg2-draft/painting.html#StrokeWidthProperty, the initial value must not be just `1`; instead the units must be explicitly included — so it needs to be `1px`.

That’s per the chain of syntax requirements from https://drafts.csswg.org/css-values-4/#typedef-length-percentage to https://drafts.csswg.org/css-values-4/#length-value to https://drafts.csswg.org/css-values-4/#dimension that the SVG spec normative includes by reference (due to citing https://www.w3.org/TR/css-values/#typedef-length-percentage) — which indicate that a `<length-percentage>` value must include units if it’s a length.

See also https://drafts.fxtf.org/fill-stroke/#stroke-width, which correctly has the initial value as `1px` instead of just `1`.

**Comment by AmeliaBR** [comment] 2018-08-18 12:28
The stroke-width syntax should actually be `<length-percentage> | <number>`, since plain numbers are valid in CSS properties, not only presentation attributes. Must have got dropped when converting to the `<length-percentage>` syntax.

But I don't see a problem with making the initial value have units, since the computed value is always converted to absolute length anyway.

**Comment by ewilligers** [comment] 2018-08-20 01:32
> The stroke-width syntax should actually be `<length-percentage> | <number>`, since plain numbers are valid in CSS properties, not only presentation attributes.

[Confirmed](https://docs.google.com/document/d/1aOJTvNCWlGpckxEbGd_zylj7Nz_kgLmrp7TXz8Wm8Fk/edit) support for plain numbers in all browsers. There are a couple of implementation bugs: Only Safari changes "10" to "10px" when serializing. Only Firefox gives "10" as the computed style. Neither has these bugs for line-height.

**Comment by sideshowbarker** [comment] 2018-08-20 04:15
> The stroke-width syntax should actually be `<length-percentage> | <number>`, since plain numbers are valid in CSS properties, not only presentation attributes.

I’m not sure what you mean by *“plain numbers are valid in CSS properties”* but as far as the CSS `stroke-width` property specifically, unit-less numbers aren’t valid values for it per https://www.w3.org/TR/fill-stroke-3/#stroke-width and https://drafts.fxtf.org/fill-stroke/#stroke-width, which both define the allowed value as `<length-percentage>`.

> Confirmed support for plain numbers in all browsers.

It’s unsurprising that browsers accept and process unit-less numbers in the value. The issue here isn’t about the processing behavior/requirements in browsers; instead it’s about the document-conformance requirements — the authoring rules.

And naively I’d assume that a goal here is to be consistent with how the CSS specs define the document-conformance requirements for CSS `stroke-width` property. And the relevant CSS specs at https://www.w3.org/TR/fill-stroke-3/#stroke-width and https://drafts.fxtf.org/fill-stroke/#stroke-width both state the allowed value is `<length-percentage>` and the initial value is `1px`.

**Comment by AmeliaBR** [comment] 2018-08-20 16:31
> I’m not sure what you mean by “plain numbers are valid in CSS properties” but as far as the CSS stroke-width property specifically, unit-less numbers aren’t valid values…


In SVG 1 _and_ SVG 2, a unitless number is always allowed as a length in a presentation attribute (even for old CSS properties like `font-size`), [where it is processed into a `px` value](https://svgwg.org/svg2-draft/types.html#presentation-attribute-css-value).

SVG 1 _also_ always allowed a unitless number as a length ["for properties defined in SVG"](https://www.w3.org/TR/SVG11/types.html#DataTypeLength), extending the CSS definition. In SVG 2, we made these syntax options explicit for properties defined in SVG 1 (changing `<length>|<percentage>` to `<length-percentage>|<number>`), and resolved not to add the same behavior for new properties.

But `stroke-width` was defined and universally implemented in SVG 1, so it needs to have the full syntax that was valid in SVG 1, including `<number>`.

**Comment by ewilligers** [comment] 2018-08-20 19:48
> We also need to validate the initial value in browsers. Maybe it is 1 after all.

When 'initial' is specified, all browsers give 'initial' as serialized value and '1px' as computed value.

**Comment by sideshowbarker** [comment] 2018-08-21 04:16
> (The "relevant CSS specs" are the same spec at different URLs, and both were created by copy & pasting the error from SVG 2!)

ah, I see — thanks

So then, can somebody raise an issue for this at https://github.com/w3c/fxtf-drafts/labels/fill-stroke-3 — or maybe better yet, a pull request there? (I’d offer to do it myself but I think it would be better done by somebody who’s familiar with the provenance.)

The reason I care about this is that the CSS validator currently reports an error for unit-less values of the CSS `stroke-width` property — because that’s what https://drafts.fxtf.org/fill-stroke/#stroke-width currently requires.

But if https://drafts.fxtf.org/fill-stroke/#stroke-width can be updated to allow `<number>`, then I can update the CSS validator to make it quit reporting an error for that.

**Comment by svgeesus** [comment] 2018-08-21 17:47
> The reason I care about this is that the CSS validator 

I'm not sure why we should care about the CSS validator. It doesn't track the specifications, doesn't handle svg in html5 well, and gives more false negatives than useful information.

**Comment by sideshowbarker** [comment] 2018-08-21 23:04
> I'm not sure why we should care about the CSS validator. It doesn't track the specifications, doesn't handle svg in html5 well, and gives more false negatives than useful information

When was the last time you tried it? I’ve actually put many hours of work this year into bringing it up to date, and @ylafon has put many more into it than I ever will.

You and @tabatkins might want to take a look through https://github.com/w3c/css-validator/commits/master

It’s pretty disheartening to have a couple of people in positions of leadership in the CSS WG expressing (and thumbs-upping) those kinds of sentiments. It’s not constructive, it doesn’t help the conversation here in any way — and it’s personally really demoralizing to me, as one of the people who’s put significant effort this year into improving the CSS validator.

You really bummed me out with that. Maybe you figure @ylafon and I should just quit caring about the CSS validator too? And quit trying to improve it?

**Comment by AmeliaBR** [comment] 2018-10-16 22:42
@dd8 Not a typo. The new spec allows multiple, layered strokes. So you could draw a thin stroke in one color on top of a thick stroke in another color.  Or a dashed stroke on top of a solid-colored stroke. The feature was initially proposed for SVG 2, but was deferred.

**Comment by dirkschulze** [comment] 2018-11-26 06:46
Fixed, closing.

**Closed by dirkschulze** 2018-11-26 06:46 UTC
Labels: Needs tests

**Comment by ewilligers** [comment] 2018-12-10 07:18
We now have WPTs and I have raised the [two browser bugs](https://github.com/w3c/svgwg/issues/529#issuecomment-414174029):
- [specified stroke-width should be able to serialize without units](https://bugs.webkit.org/show_bug.cgi?id=192550)
- [stroke-width computed value should not be number](https://bugzilla.mozilla.org/show_bug.cgi?id=1512926)
