### ISSUE TITLE
Unit of numbers in path data

### ISSUE THREAD

**Issue by SimonSapin** [w3c/svgwg#144] opened 2016-05-23 14:25 UTC
Reading https://svgwg.org/svg2-draft/paths.html#PathDataEllipticalArcCommands , it wasn’t clear to me what’s the unit of the  x-axis-rotation angle in an arc path command. I’ve had to look at examples to find out it’s in degrees. This should be defined in normative text.

(Compare with the new "bearing" command which specifies: "The parameter is an angle in degrees, where 0 indicates the direction of the positive x-axis".)

Similarly, it seems "obvious" that coordinates and other lengths are measured in user units, but I couldn’t find a normative definition for that either.

**Comment by AmeliaBR** [comment] 2016-05-23 20:08
Thanks Simon.  If you want to propose specific new language as a pull request that would be great.  Otherwise, the issue is now marked for final cleanup before CR stage.

**Comment by nikosandronikos** [comment] 2016-05-31 06:50
Addressed in 77ee7388622fb7a5b19ca08451e370a13b8795f3

**Closed by nikosandronikos** 2016-05-31 06:50 UTC
Labels: Needs editing, Paths chapter, SVG 2
