### ISSUE TITLE
Number syntax: digit-sequence "."

### ISSUE THREAD

**Issue by dirkschulze** [w3c/svgwg#442] opened 2018-05-10 10:36 UTC
SVG Path data as well as SVG transforms and probably other SVG specific attributes that take numbers allow: `1.`.

It seems only Edge does support this:
https://codepen.io/krit/pen/wjmzzQ
https://codepen.io/krit/pen/rvdOQX

Should this be removed? Do we just need more tests?

Note: CSS numbers do not support this syntax either.

https://www.w3.org/TR/SVG/paths.html#PathDataBNF
https://www.w3.org/TR/SVG/coords.html#TransformAttribute (replaced by CSS Transforms but sill relevant since the number syntax should be defined the same for all appearances. https://github.com/w3c/csswg-drafts/issues/2623#issuecomment-388005994)

**Comment by dirkschulze** [comment] 2018-05-10 10:47
Adobe Illustrator does support this syntax as well.

@dstorey @AmeliaBR @longsonr could you chime in please and say what you think about this?

**Comment by dirkschulze** [comment] 2018-05-10 14:54
As an interesting note: The `x`, `y`, `width` and `height` attributes do support the `digit-sequence "."` syntax in Safari, Chrome and Edge but not in Firefox.

https://codepen.io/krit/pen/JvLrbv

**Comment by AmeliaBR** [comment] 2018-05-10 15:19
This is a duplicate of https://github.com/w3c/svgwg/issues/331.

Could you add your comments there, Dirk?

**Closed by AmeliaBR** 2018-05-10 15:19 UTC
Labels: Paths chapter

**Comment by dirkschulze** [comment] 2018-05-10 16:36
@AmeliaBR Thanks. I did create and added a summary there.

**Comment by dirkschulze** [comment] 2018-05-10 18:26
@longsonr as @AmeliaBR said, comment on #331 please.
