### ISSUE TITLE
Error about drawto_command in SVG 2.0 path EBNF

### ISSUE THREAD

**Issue by ish-kafel** [w3c/svgwg#929] opened 2024-01-06 08:47 UTC
It seens like SVG 2.0 does not support `wsp` in different `drawto_command` but SVG 1.1 does, is that an error?

in [SVG 2.0](https://svgwg.org/svg2-draft/paths.html#PathDataBNF):
```
svg_path::= wsp* moveto? (moveto drawto_command*)?

drawto_command::=
    moveto
    | closepath
    | lineto
    | horizontal_lineto
    | vertical_lineto
    | curveto
    | smooth_curveto
    | quadratic_bezier_curveto
    | smooth_quadratic_bezier_curveto
    | elliptical_arc
```
in [SVG 1.1](https://www.w3.org/TR/SVG11/paths.html#PathDataBNF):
```
svg-path:
    wsp* moveto-drawto-command-groups? wsp*
moveto-drawto-command-groups:
    moveto-drawto-command-group
    | moveto-drawto-command-group wsp* moveto-drawto-command-groups
moveto-drawto-command-group:
    moveto wsp* drawto-commands?
drawto-commands:
    drawto-command
    | drawto-command wsp* drawto-commands
drawto-command:
    closepath
    | lineto
    | horizontal-lineto
    | vertical-lineto
    | curveto
    | smooth-curveto
    | quadratic-bezier-curveto
    | smooth-quadratic-bezier-curveto
    | elliptical-arc
```

**Comment by dalboris** [comment] 2024-01-06 12:42
Yes you are correct, but this is a duplicate of https://github.com/w3c/svgwg/pull/778

**Comment by ish-kafel** [comment] 2024-01-06 14:07
thanks for your mention!

**Closed** 2024-01-06 14:07 UTC
