### ISSUE TITLE
Values in SVGZoomAndPan and SVGUnitTypes should be accessible to javascript

### ISSUE THREAD

**Issue by longsonr** [w3c/svgwg#291] opened 2016-10-16 11:36 UTC
Please:
The [SVG 2 specification](https://www.w3.org/TR/2016/CR-SVG2-20160915/types.html#InterfaceSVGZoomAndPan)

Makes it impossible to write var x = ZoomAndPan.SVG_ZOOMANDPAN_UNKNOWN as ZoomAndPan is [NoInterfaceObject].

Similarly with SVGUnitTypes.

This is not what either Chrome or Firefox do (both support accessing the ZoomAndPan interface values directly). In fact Firefox has tests that contain SVGUnitTypes so it's certainly likely that there's also usage of this in the wild.

I propose changing the ZoomAndPan interface to

```
interface SVGZoomAndPan {
};

SVGZoomAndPan implements SVGZoomAndPanValues;
```

Then having this as SVGZoomAndPanValues

```
[NoInterfaceObject]
interface SVGZoomAndPanValues {

  // Zoom and Pan Types
  const unsigned short SVG_ZOOMANDPAN_UNKNOWN = 0;
  const unsigned short SVG_ZOOMANDPAN_DISABLE = 1;
  const unsigned short SVG_ZOOMANDPAN_MAGNIFY = 2;

  [SetterThrows]
  attribute unsigned short zoomAndPan;
};
```

And all existing users of ZoomAndPan i.e. SVGSVGElement and SVGViewElement would then implement SVGZoomAndPanValues

This would mean that an SVGSVGElement would not be an SVGZoomAndPan but you would be able to access its contents.

Similarly for SVGUnitTypes.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1241899 and https://bugzilla.mozilla.org/show_bug.cgi?id=1241898 for the Firefox implementation which is landing now. This will align Firefox with Chrome's implementation.

**Comment by nikosandronikos** [comment] 2016-10-17 04:52
That seems reasonable to me - and has the approval of some other WG members I see.

For posterity, the reason for the extra [NoInterfaceObject] SVGZoomAndPanValues interface, is due to a desire to separate mixins and regular interfaces.

**Comment by foolip** [comment] 2016-10-17 13:17
Chrome actually does not expose the `SVGZoomAndPan` interface, Chrome 28 was the last version to do so. Safari 10 does also not have it, but I can confirm that Edge 14 and Firefox 51 do.

`SVGZoomAndPan.prototype` is undefined both Edge and Firefox, does WebIDL say something to make it so? I can't find it, but it may be in there somewhere.

`SVGUnitTypes` is different in that it has only constants, and it seems universally exposed. How about just dropping `x implements SVGUnitTypes` everywhere?

**Comment by longsonr** [comment] 2016-10-17 17:35
We'd have x implements SVGUnitTypeValue which would be a [NoInterfaceObject] and contain the constants. SVGUnitTypes would then contain nothing but also implement SVGUnitTypeValues. https://bugzilla.mozilla.org/show_bug.cgi?id=1241898  has more details.

**Comment by foolip** [comment] 2016-10-18 08:32
Context: I was pointed here by @fsoder in https://codereview.chromium.org/2415413002/

Here's a test for whether `x implements SVGUnitTypes` is already supported:
https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4581

Edge 14 and Firefox 51 have the constants everywhere. Chrome 55 and Safari 10 don't have them.

A search for "SVG_UNIT_TYPE_" in httparchive:har.2016_09_15_chrome_requests_bodies finds
[66 results](https://github.com/w3c/svgwg/files/535601/results-20161018-102112.csv.txt). 64 of them are from api-maps.yandex.ru and the other two are https://boxy-svg.com/api/frontend/modules.js and http://www.javascripture.com/javascripture.js. All of the are using the SVGUnitTypes object, and so don't depend on `x implements SVGUnitTypes`.

@longsonr, given the lack of interop and seemingly low usage in the wild, would you be willing to drop `x implements SVGUnitTypes` from Gecko? To me it doesn't seem to add anything if `SVGUnitTypes` itself is exposed.

**Comment by longsonr** [comment] 2016-10-18 21:04
@foolip I think we'll land https://bugzilla.mozilla.org/show_bug.cgi?id=1241898 as is and then think about removing the implements later. I.e. one step at a time. Feel free to add another bug in bugzilla to track that idea though.

**Comment by nikosandronikos** [comment] 2016-10-18 23:06
> Feel free to add another bug in bugzilla to track that idea though.

And file a separate issue here too please.

**Comment by foolip** [comment] 2016-10-19 20:27
The questions of `NoInterfaceObject` and what `implements` what are connected, so for the spec discussion I couldn't formulate an orthogonal or even follow-up issue. Concretely, my suggested fixes for `SVGZoomAndPan` and `SVGUnitTypes` would be:
* Leave `SVGZoomAndPan` as a mixin interface, with `[NoInterfaceObject]` and a bunch of interfaces implementing it.
* Make `SVGUnitTypes` a normal interface by dropping `NoInterfaceObject` and having nothing implement it.

**Comment by foolip** [comment] 2016-10-19 21:25
> Making SVGZoomAndPan [NoInterfaceObject] will mean that you can't use its constants directly

The constants would be on SVGSVGElement and SVGViewElement together with the zoomAndPan attribute itself, doesn't that suffice?

> Dropping SVGUnitTypes means that you can only use its constants directly.

The suggestion is to keep it, so that the kind of code found in https://github.com/w3c/svgwg/issues/291#issuecomment-254442089 keeps working.

**Comment by nikosandronikos** [comment] 2016-10-20 02:27
> Leave SVGZoomAndPan as a mixin interface, with NoInterfaceObject and a bunch of interfaces implementing it.

This would be a breaking change from SVG 1.1 SE. How confident are you that it would have a negligible impact?

**Comment by foolip** [comment] 2016-10-20 08:52
The multiple inheritance of SVG 1.1 was never possible to implement in JavaScript bindings, I assume that's why implementations took different paths. Per https://github.com/w3c/svgwg/issues/291#issuecomment-254204205 Chrome and Safari don't have a `window.SVGZoomAndPan`, which is a good start.

A search for "SVGZoomAndPan" in httparchive:har.2016_09_15_chrome_requests_bodies finds only [64 results](https://storage.googleapis.com/blink-httparchive-export/SVGZoomAndPan.json). None of the access anything on SVGZoomAndPan, AFAICT it's all one of two things:
* Fingerprinting: http://p.smrk.io/jic/rr.php?b=da39a3ee5e6b4b0d3255bfef95601890afd80709
* Part of a huge list of globals: https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.js

Finding literally no real usage in httparchive is pretty unusual even for obscure things, so I'd say this is a safe change.

**Comment by longsonr** [comment] 2016-10-25 21:40
The changes as originally outlined have now landed in Firefox nightlies.

**Comment by foolip** [comment] 2016-10-25 21:52
Landing [`Make SVGUnitTypes [NoInterfaceObject]`](https://hg.mozilla.org/mozilla-central/rev/c73e584c4071) given that it is currently exposed everywhere doesn't seem like a good idea, even if what's the spec currently says. See https://github.com/w3c/svgwg/issues/291#issuecomment-254442089 for pages in the wild that read the constants on SVGUnitTypes. @bzbarsky @heycam

**Comment by longsonr** [comment] 2016-10-25 22:24
@foolip  That's not what's happened. Read the bugs carefully and what's actually been proposed here.

**Comment by bzbarsky** [comment] 2016-10-25 23:20
Yeah, that commit has a .... really terrible commit message that has no bearing on what the commit actually does.  :(  That's rather unfortunate.  You have to read the actual IDL changes to have any idea what it actually does.

**Comment by foolip** [comment] 2016-10-26 10:45
Oh, so AFACIT that commit doesn't change observable behavior, is that right?

**Comment by longsonr** [comment] 2016-10-26 12:17
@foolip

Sure it does, that's why this github issue exists.

Elements such as SVGMaskElement will not be SVGUnitType objects, although they will still allow access to the constants and members of that interface.

**Comment by foolip** [comment] 2016-10-26 12:26
Oh, `document.createElementNS('http://www.w3.org/2000/svg','mask') instanceof SVGUnitTypes` was true in Gecko before, fascinating. That returns false in Chrome/Safari and throws in Edge.

How did that actually work, is it `implements X` itself that caused `instanceof X` to be true? Are there any other odd cases like that left?

**Comment by bzbarsky** [comment] 2016-10-26 15:22
> How did that actually work

Because Gecko implements https://heycam.github.io/webidl/#es-interface-hasinstance (as of today's draft; I wish we had something resembling stable links, because this part might get removed from the spec because no one except Gecko implements is).

But also, in IDL spec terms, the thing we are really after is separating out the concepts of "interfaces" and "mixins".  We are trying to get to a point where things on the right-hand side of an "implements" statement are always [NoInterfaceObject] interfaces, at which point we can drop the ability to "implements" an interface and have explicit mixin syntax.

**Comment by bzbarsky** [comment] 2016-10-26 17:08
Or more precisely, the current IDL in the SVG spec doesn't block it, but breaks backwards compat.  @longsonr's proposal keeps the desirable property of not conflating mixins and interfaces, but restores backwards compat.

**Comment by foolip** [comment] 2016-11-09 20:32
@bzbarsky, I guess "If V is a platform object that implements the interface for which O is the interface prototype object, return true" is the relevant bit here? That's interesting, I had no idea that was ever intended to work, or indeed that it did work in Gecko.

In any case, the goal of "things on the right-hand side of an "implements" statement are always [NoInterfaceObject] interfaces" is clearly a good one, and before this issue I assumed that it was already so, or otherwise a mistake.

As for compat, I think https://github.com/w3c/svgwg/issues/291#issuecomment-254930687 has a good chance of working out. For Gecko, the SVG_UNIT_TYPE_* constants would go away in a few places, but per https://github.com/w3c/svgwg/issues/291#issuecomment-254442089 it ought be quite low risk.

**Comment by bzbarsky** [comment] 2016-11-09 20:52
I don't have specific opinions on what the spec should say here, apart from the mixin business.  Going to defer to @longsonr on that.

**Comment by bzbarsky** [comment] 2016-11-09 20:52
@foolip Oh, and yes, your quoted piece of the IDL spec is what affects instanceof behavior.

**Comment by longsonr** [comment] 2016-11-09 21:27
Happy to try having the constants only on SVGUnitTypes in a future release of Firefox provided other UAs are on board too.

**Comment by foolip** [comment] 2016-11-09 21:51
No change would be required for Chrome and Safari. Who's the SVG contact for Edge to comment on this? @travisleithead, can you poke someone?

**Comment by nikosandronikos** [comment] 2016-11-10 00:15
@atanassov or @boggydigital ?

**Comment by boggydigital** [comment] 2016-11-11 21:46
LGTM

**Comment by foolip** [comment] 2016-11-16 16:10
@boggydigital, to make it explicit, is the proposal in https://github.com/w3c/svgwg/issues/291#issuecomment-254930687 that LGTY, or what was originally proposed in this issue?

**Comment by boggydigital** [comment] 2016-11-16 17:41
The latest one in https://github.com/w3c/svgwg/issues/291#issuecomment-254930687

**Comment by foolip** [comment] 2016-11-16 21:01
OK, thanks @boggydigital!

@nikosandronikos, what does the "Needs WG input" label mean, is there anything more needed?

**Comment by AmeliaBR** [comment] 2016-11-16 21:21
@foolip 

"Needs WG input" means that something needs discussion, to decide what the spec should say. Which has been happening here nicely. (It makes me so glad for moving to GitHub: this is exactly how it is supposed to work!)

At this point, I think we can probably make a resolution on it at our call tomorrow (Thurs afternoon in North America). Are you able to prep a pull request of exactly what changes need to be made to the spec text?

**Comment by foolip** [comment] 2016-11-16 22:01
I haven't edited this spec before, but it seemed simple enough: https://github.com/w3c/svgwg/issues/295

**Comment by nikosandronikos** [comment] 2016-11-17 05:22
@longsonr You haven't commented on @foolip's suggestion regarding SVGZoomAndPan:

>     Leave SVGZoomAndPan as a mixin interface, with NoInterfaceObject and a bunch of interfaces implementing it.

My preference would be to accept @foolip's proposal for SVGUnitTypes and @longsonr's proposal for SVGZoomAndPan, but I'm happy to defer to the implementers on this one.
I'd like to hear solid support for both aspects of the proposal before we resolve on it.

**Comment by foolip** [comment] 2016-11-17 11:01
The reasons I've suggested making SVGZoomAndPan as-is in the spec:
 * It already has [NoInterfaceObject] in Chromium and WebKit (https://github.com/w3c/svgwg/issues/291#issuecomment-254204205)
 * A search in httparchive found no content depending on it. (https://github.com/w3c/svgwg/issues/291#issuecomment-255047561) (This is unusual, it's a big dataset and even the weirdest things tend to show up if you look for it.)

**Comment by longsonr** [comment] 2016-11-17 19:38
I don't see the point in making the constants in SVGZoomAndPan inaccessible to javascript so I expect Firefox will stay as it now is in that regard.

**Comment by AmeliaBR** [comment] 2016-11-17 20:08
SVGZoomAndPan is pretty much useless due to the current lack of browser support for user-controlled zoom and pan, which explains the lack of usage.  You'd need to search demos from the Adobe SVG Viewer days to find practical uses for it.

I'm more concerned about consistency. Why have some shared constants only available from a static interface, and others only available from the implementing interfaces?

**Comment by foolip** [comment] 2016-11-17 20:32
Regarding consistency, the only way to achieve that would be to have the constants everywhere, but that wouldn't be consistent with the rest of the platform, and apparently not needed for web compat. By making SVGUnitTypes a normal interface, that becomes the only wart.

Needless to say, if one weren't constrained at all by web compat, then none of these things would be numerical constants at all.

**Comment by AmeliaBR** [comment] 2016-11-17 21:57
We talked about the issue on our call today. Since we've got 3 different implementers giving the OK for SVGUnitTypes to be an ordinary interface with no mixin, we're okay with that.  

@shepazu is going to look in to getting the W3C permissions sorted for @foolip in order to merge that pull request.  We may need to temporarily add you to the GitHub SVG team, but I don't *think* that means you have to be formally assigned as a Google rep on the WG.  If it gets too complicated, one of the WG members can make the edits.

_____________________


For SVGZoomAndPan, we hope to get consensus from you all before making a change (if any).

Things to consider (my personal opinion):

- The attribute/behavior that these constants correspond to isn't implemented in any actively-developed user agent, and we've currently got it marked as "at risk" in the spec.

- Even without seeing the data, I'm pretty sure that usage of the constants from the SVGSVGElement and SVGViewElement interfaces is just as low (meaning, essentially zero) as for the direct usage of the SVGZoomAndPan interface.

As much as I'd love to see proper browser implementations of user zoom & pan control for graphics, I suspect that when that comes it will be via a new functionality that works for all web content, not just SVG, and that is compatible with existing pinch-zoom implementations.  (And hopefully, it will be via a mechanism that doesn't "disable" zoom, it only defines which container isolates the zoom.)

**Comment by nikosandronikos** [comment] 2016-11-17 23:43
My take on exposing exposing SVGZoomAndPan as an interface is that I agree doing that will still have some level of inconsistency, but I think that's where authors will expect to find the constants, and that's the consistency that matters.

**Comment by foolip** [comment] 2016-11-18 09:25
For SVGZoomAndPan, @fsoder said in https://codereview.chromium.org/2415413002/#msg22 that he'd prefer "nuke from orbit", so if there's any appetite for removing it entirely that might be worth a try. FWIW, there is a use counter for the zoomAndPan attribute in Chrome, and it's pretty low:
https://www.chromestatus.com/metrics/feature/timeline/popularity/1102

In the meantime, exposing the interface would only increase the risk of eventual removal, and whatever authors may initially expect, in https://github.com/w3c/svgwg/issues/291#issuecomment-255047561 no content was found that actually tried to access the constants on the interface.

**Comment by nikosandronikos** [comment] 2016-11-22 23:26
Re-opening, because PR #295 only resolved half the issue - we haven't resolved on whether SVGZoomAndPan will stay the same or not yet.

**Comment by AmeliaBR** [comment] 2018-01-29 19:57
Does anyone have any outstanding issues on this, or can this be closed?

Teleconference minutes (reposting what Github-bot posted in the wrong issue):

The Working Group just discussed `Values in SVGZoomAndPan and SVGUnitTypes should be accessible to javascript`.

<details><summary>The full IRC log of that discussion</summary>
&lt;Chris__> topic: Values in SVGZoomAndPan and SVGUnitTypes should be accessible to javascript<br>
&lt;Chris__> github: https://github.com/w3c/svgwg/issues/291<br>
&lt;krit> AmeliaBR: we have interfaces that are defined as NoInterfaceObject but other object types which implement these infterfaces which have those properties on them<br>
&lt;krit> AmeliaBR: so you could access those constants but not as a static item<br>
&lt;krit> AmeliaBR: usually constants are property of a class<br>
&lt;krit> AmeliaBR: need to recall. it is from 2016<br>
&lt;krit> krit: those are mixing and get implemented by those classes. So they actually are part of those classes implementing them.<br>
&lt;krit> krit: not sure where the issue is?<br>
&lt;krit> AmeliaBR: those are legacy features and not used on the web. Keep them close to SVG 1.1<br>
&lt;krit> AmeliaBR: not sure what is required.<br>
&lt;krit> krit: are those interfaces implemented already?<br>
&lt;krit> krit: we were asked to re-add interfaces not because they are used but because they are implemented widely<br>
&lt;AmeliaBR> Here's the last update on implementation https://github.com/w3c/svgwg/issues/291#issuecomment-254204205<br>
&lt;krit> Chris__: so we have interfaces that are not used but implemented.<br>
&lt;krit> Chris__: seems like some ppl argue it shouldn't be exposed.<br>
&lt;AmeliaBR> SVGUnitTypes was implemented, and was re-introduced to the spec. SVGZoomAndPan wasn't well implemented cross-browser, and that's whay it wasn't changed at the time.<br>
&lt;krit> Chris__: Firefox seems to expose and implement it directly and does seem to have tests<br>
&lt;krit> AmeliaBR: there are 2 different causes.<br>
&lt;krit> AmeliaBR: no decision has been made and issue was reopened. Not implemented browsers anyways.<br>
&lt;krit> krit: they are not implemented? because I think they are.<br>
&lt;AmeliaBR> s/no decision/for SVGZoomAndPan/<br>
&lt;Chris__> https://bugzilla.mozilla.org/show_bug.cgi?id=1241898<br>
&lt;krit> Chris__: original comment was about aligning implementations so we have 2 implementations, Blink and Firefox<br>
&lt;AmeliaBR> s/for SVGZoomAndPan/for SVGZoomAndPan, no decision/<br>
&lt;krit> ericwilligers: we could still remove those interfaces if they are not sued<br>
&lt;krit> s/sued/used/<br>
&lt;krit> Chris__: yes we could<br>
&lt;krit> Chris__: not sure what is proposed is better<br>
&lt;krit> AmeliaBR: I don't think we are getting anywhere on this on the call. We should ping ppl if this is still an issue or if they are happy with changes that were made.<br>
&lt;krit> Chris__: agree. Will post on the issue and ask for comments.<br>
&lt;Chris__> github: https://github.com/w3c/svgwg/issues/269<br>
</details>

**Comment by foolip** [comment] 2018-01-31 12:34
For SVGUnitTypes, things appear to be the same as they were in https://github.com/w3c/svgwg/issues/291#issuecomment-254442089. I confirmed this in Chrome, Firefox and Safari, but Edge actually crashes when loading https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4581. I think the spec is fine as-is there, and this is tested in https://wpt.fyi/svg/historical.html.

For SVGZoomAndPan, https://svgwg.org/svg2-draft/types.html#InterfaceSVGZoomAndPan has `[NoInterfaceObject]`, which I also think is the right thing, since SVGZoomAndPan is the target of `implements` statements: `SVGSVGElement implements SVGZoomAndPan` and `SVGViewElement implements SVGZoomAndPan`. Also tested in https://wpt.fyi/svg/historical.html.

I didn't report the issue, but I'm satisfied.

**Comment by travisleithead** [comment] 2018-01-31 21:47
Thanks @foolip (I also reported the crashing site, so we can fix it.)

**Comment by longsonr** [comment] 2018-02-04 17:15
https://bugzilla.mozilla.org/show_bug.cgi?id=1435568 should make us align with Chrome for SVGUnitTypes i.e. individual elements won't implement SVGUnitTypes

**Comment by longsonr** [comment] 2018-02-05 21:37
What's happening with ZoomAndPan. Is it to be removed altogether? Keeping it and making it [nointerfaceobject] makes no sense as far as I can see.

**Comment by AmeliaBR** [comment] 2018-02-05 22:17
`SVGZoomAndPan`, unlike `SVGUnitTypes` is still used as mixin (it is implemented by [`SVGSVGElement`](https://svgwg.org/svg2-draft/struct.html#InterfaceSVGSVGElement) ).

So there is still access to the named constants through any `<svg>` element instance.

**Comment by dstorey** [comment] 2018-05-05 00:25
Are we happy to close this one now?

**Comment by longsonr** [comment] 2018-05-05 06:08
I still think that making people write SVGUnitTypes.SVG_UNIT_TYPE_USERSPACEONUSE yet then saying you can't write SVGZoomAndPan.SVG_ZOOMANDPAN_DISABLE, you must write SVGSVGElement.SVG_ZOOMANDPAN_DISABLE is strangely inconsistent. At the moment Firefox allows SVGZoomAndPan.SVG_ZOOMANDPAN_DISABLE to try to avoid this confusion but also SVGSVGElement.SVG_ZOOMANDPAN_DISABLE to avoid breaking anyone who might write things the spec way.

Should SVGZoomAndPan be removed altogether though? Is it useful/functional anywhere?

**Comment by dstorey** [comment] 2018-05-05 07:39
I'm actually not even sure it should be a mixin. According to WebIDL:

> Interface mixins allow the sharing of attributes, constants, and operations across multiple interfaces. If you’re only planning to extend a single interface, you might consider using a partial interface instead.
https://heycam.github.io/webidl/#using-mixins-and-partials

As It is only included on SVGSVGElement, the WebIDL advice is to make it a partial. But as they're both in SVG, they should probably just be added to SVGSVGElement directly (assuming we want to keep them)

**Comment by longsonr** [comment] 2018-05-05 07:42
SVGZoomAndPan is not just on SVGSVGElement, it's on SVGViewElement too.

**Comment by dstorey** [comment] 2018-05-05 07:44
Oh yes, I was confused by the comment above. I spotted that after commenting when scrolling up. Ignore the previous comment :D

**Comment by dstorey** [comment] 2018-05-05 08:11
As far as is if it is useful. The docs I've found for Edge say "The zoomAndPan attribute is not supported, except for the default magnify operation". A quick look at the code, I saw a comment that says zoomAndPan isn't implemented, so it looks like we have a very barebones implementation that doesn't do anything.

**Comment by boggydigital** [comment] 2018-06-11 19:17
Not blocking updated 2.0 CR publication - assigning 2.1 WD milestone

**Comment by AmeliaBR** [comment] 2019-07-14 21:28
Oops. Looks like our resolution above was redundant. The change to SVGUnitTypes already went through in https://github.com/w3c/svgwg/pull/415, the issue was staying open because of SVGZoomAndPan.

But since the decision in #56 was to drop the zoom and pan attribute & its IDL reflection, the constants will be dropped too, so this issue can be closed.

**Closed by AmeliaBR** 2019-07-14 21:28 UTC
Labels: Basic Data Types and Interfaces chapter, Needs WG input, Needs editing, SVG Core
