### ISSUE TITLE
SVG2 spec means elements within a <use> tag can not be targeted for styling 

### ISSUE THREAD

**Issue by peter-mouland** [w3c/svgwg#367] opened 2017-11-15 14:55 UTC
**spec:** https://www.w3.org/TR/SVG2/struct.html#UseStyleInheritance
**CodePen Demo:** https://codepen.io/peter-mouland/pen/pdEMWZ/

Recently, I have tried to create a number of SVG's and reuse those SVG's within the same document via the &lt;use> tag.  These 're-used' svgs need to have different styles applied to them, and to the elements within. 

Following the **SVG1** spec this worked as expected. You can see a CodePen Demo<sup><a href='#1'>1</a></sup> of this working with Chrome 62.  This also works when using CSS custom properties (see CodePen demo<sup><a href='#2'>2</a></sup>)

Following the **SVG2** spec no SVG's are viewable. View the same demo on Firefox 56, which has implemented the SVG2 spec (See discussion<sup><a href='#3'>3</a></sup>).  This is also no longer achievable using CSS Custom Props (see CodePen demo<sup><a href='#2'>2</a></sup>).

Using the demo as an example for the SVG2 spec, is there another way I am able to achieve this in browsers implementing SVG2? Or is this an area that requires some more thought?

### Links:
 - <a name="1">1</a> [CodePen Demo using multiple symbols](https://codepen.io/peter-mouland/pen/pdEMWZ/)
 - <a name="2">2</a>[CodePen Demo using CSS custom properties](https://codepen.io/peter-mouland/pen/MOpeJw?editors=1100)
 - <a name="3">3</a> [Bugzilla Firefox discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=1415186): _Firefox does not display colours: as per SVG2 spec_
 - 4 [Chromium bug raised](https://bugs.chromium.org/p/chromium/issues/detail?id=785234#c2): _chrome display colours: as per v1 spec_
 - 5 [Chromium SVG2 bug Raised](https://bugs.chromium.org/p/chromium/issues/detail?id=785246&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=)
 - 6 [Edge Bug Report](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14673751/): _Edge displays colours: as per v1 spec_

### additional info email to w3c: 21 Nov 2017
 > I think this would classify as a breaking change between the 2 specs (according to feedback gathered from a number browser venders). I'm not sure if it was intended, or an unfortunate side-effect, either way, I just want to style my inline-svg's with as little duplicate code as possible 🤔
> 
> I hope you are able to follow my ramblings and either update the spec to allow re-used SVG's to have custom styling applied, or perhaps document another solution to this problem.  Thanks for any help!

**Comment by AmeliaBR** [comment] 2017-11-21 18:07
You're correct that this is technically a breaking change in the spec. However, it was a section of the spec that was never consistently implemented in web browsers.  The [note and example in the spec](https://www.w3.org/TR/SVG2/struct.html#UseStyleInheritance) explains what changed and why (to be consistent with web components shadow DOM, and to avoid many current bugs with interactive and animated styles).

The workaround is to avoid CSS selectors that depend on the position of the original element within the original DOM (like `svg.class  path.inside-symbol`).  The paths in the cloned copies of the symbols will not match these selectors, because they are no longer descendants of the `svg.class`.

If you want the styles to persist in the clones, you can put the classes on the `symbol` or `path` elements directly, since those classes would be copied to the clone.  Here's a version of your pen that does that, and therefore works in Firefox:

https://codepen.io/AmeliaBR/pen/4ccc55d55673d8467850bd9ce55be6f1?editors=1100

I also fixed the Safari problem, which wasn't related to style matching.  Safari does not yet support the `href` attribute without the `xlink` prefix.

________________________________

All that said: if other browser developers / spec editors want to propose a different spec that is closer to how SVG 1.1 (and most current browsers) work, that's still an option.  But then we'd need to clarify how things like animations and interactive pseudoclasses work (which is currently a mess of inconsistency cross-browser).

**Comment by peter-mouland** [comment] 2017-11-22 13:23
Thanks a lot for taking a look at that (and for spotting the `xlink` oversight!).

With your update, the restyling working across all browsers.  It also works perfectly with CSS Custom Props and only a single SVG Symbol which is ideal (rather than one symbol per style).

https://codepen.io/peter-mouland/pen/MOpeJw

Thanks again

**Comment by markofca** [comment] 2017-12-09 09:33
We just found our way to this thread after the breaking change killed our site in the newest versions of Firefox.  I'd like to express my dismay at this change to the spec and strongly ask/suggest/beg/implore that it be reconsidered in the SVG 2 spec.  

The V1 approach was significantly better.  The V2 approach essentially violates the underlying premise and value of CSS, largely eliminates the value of <use>, and, I would argue, makes it impossible to do interesting and complex things with SVG. 

I can see why the implementation would be significantly simpler, but the new approach has the potentially to largely undermine SVG as a useful tool, and 100% of the browsers already had working implementations of the SVG 1 approach (albeit not quite standardized).

CSS was intended to allow you to style objects based on their context.  Unless I'm missing something, the new 'improvement' is styling a template statically and then reinstantiating the styled element.  If we've learned anything in the last decade, it's that styling elements based on their context is a good thing.  CSS was such a bit hit because we could now put the same HTML in two places and have it do wildly different things based on styling rules.  It largely fulfilled the dream of separating structure from style.

SVG2 appears to eliminate this possibility for SVG elements that are instantiated with <use>, which kills the usefulness of <use>, which then leads to having to repeat code everywhere just so you can style it.  This is demonstrated in the codepen solution.  The structure of the chevron is repeated twice just to get two different styles.  

To use a mediocre analogy of cookie cutters and cookies, SVG 2 appears to allow us to only style the cookie cutters but not the cookies.  And if you've ever decorated cookies, you know that the interesting part is that each cookie shares a structure but can be decorated with different styles on a per cookie basis.  We might have a cookie cutter for a star, and a moon, and a little man (structure).  But from those three cutters, we then instantiate many cookies and with unique icing and M&M decoration (style).

With SVG 2, now we appear to have to create 1000 cookie cutters.  Further, having them adjust based on the dynamic nature of web pages is now impossible.  This is truly a step backward.  For styling to be useful, you need to be able to style each individual element based on its position and context in the DOM.  If styling has been handicapped to the point that it can't cross the shadow DOM barrier, it's no longer useful since we can't use the DOM context to determine the style.  

Cookies that appear in a "Christmas" div should have red and green stripes and cookies that appear in an "Easter" div should have pink and blue stripes, and sometimes pink and yellow stripes if the cookie has been marked as "selected" by the user.  

Without complex selectors that cross the DOM boundary, <use> is reduced to acting like a server-side include. Yes, if I want 1000 cookies, 500 of which are identical to one template and 500 of which are identical to another (the chevron example), then the SVG 2 spec makes sense.  But this is not the common or interesting case.  

If I've missed something and there's a way to style an individual sub-element within a <use> instantiation based on where that <use> appears in the DOM, then forgive my passionate plea.  But if SVG 2 just made basic CSS styling based on context impossible, then please (!!) reconsider, particularly given that it was already implemented and working in every major browser.

**Comment by dholbert** [comment] 2017-12-09 16:38
Here's a [sample testcase for what @markofca is trying to achieve](https://bug1424466.bmoattachments.org/attachment.cgi?id=8935996).

Is there any way to `<use>` the `#target` element there, and customize styles in the different `<use>` clones?  (The testcase attempts to do that, and it works in all browsers except for Firefox 56+ which have implemented the new spec text.)

**Comment by AmeliaBR** [comment] 2017-12-09 16:42
(reopening issue for further discussion, although I think we're talking about a few different things here)

**Comment by markofca** [comment] 2017-12-09 18:46
Thanks for reopening.  It's likely that my concern does mix different issues and apologies if my terminology isn't quite right, but @dholbert summarizes my issue well:  How can you target a subelement within an SVG clone for styling?

Another use case to help add context to the problem: building a game in which the characters and opponents are complex SVG (let's say a couple pages of path elements per character).  These characters have N different visual attributes (health, strength, uniform color, etc) that vary each with M different potential values.  The values change depending on the scenario and the state of the character at any time.  You have P opponents in a battle whose N x M values are changing individually.

In SVG 1, the implementation is easy.  You create one character, clone it P times, and then add / remove classes to the clones to configure the N x M values dynamically.

In SVG 2, the implementation is basically "sprites".  You have to create N x M versions to clone at the outset and then dynamically and somehow seamlessly swap in different versions to show different states.  This is largely impossible and unwieldy for any interesting values of N and M.  So, instead, you end up creating P elements, each with the two pages of code repeated, so you can style them dynamically.  That is, you can either have the value of `<use>` (repeating structure) or the value of CSS (styling elements individually), but not both at the same time.

**Comment by peter-mouland** [comment] 2017-12-09 20:39
I believe with CSS Custom Properties you can achieve what you need, but this obviously means it won't work in Internet Explorer or Edge < 16.  Hopefully supporting 'modern' browsers is enough for you, but i guess it doesn't change the fact about the breaking change, and each element can be styled/themed according to each 'state'  as required.


My second link tried to demonstrate this technique: https://codepen.io/peter-mouland/pen/MOpeJw
This has a single SVG, which is then used multiple times:

```svg
<svg class="symbol">
  <symbol id="chevron" viewBox="0 0 100 60" >
    <line class='line line--1' x1="50" y1="50" x2="10" y2="10" stroke-width="10" stroke-linecap="round"></line>
    <line class='line line--2' x1="50" y1="50" x2="90" y2="10" stroke-width="10" stroke-linecap="round"></line>
  </symbol>
</svg>
<svg class="a-state" width="4em" height="40px"><use xlink:href="#chevron"></use></svg>
<svg class='another-state' width="4em" height="40px"><use xlink:href="#chevron"></use></svg>
```

```css
.symbol { display: none; }

/* Set default theme  */
:root { 
  --line-1: brown;
  --line-2: green;
}
/* Set another theme */
.another-state {
  --line-1: red;
  --line-2: blue;  
}

/* Apply Themes */
.line {
    stroke: var(--line-1);
}
.line--2 {
    stroke: var(--line-2);
}
```

which produces: 
<img width="174" alt="screen shot 2017-12-09 at 20 31 46" src="https://user-images.githubusercontent.com/1727939/33799259-0582b4f0-dd20-11e7-9353-a8894942d7f6.png">

I think this is what you are trying to get, but i could have misunderstood.  Plus i'm not sure if browser support is important to you or if you trying to raise general awareness about the breaking change in the spec... either way hope this helps!

**Comment by dholbert** [comment] 2017-12-09 22:15
Thanks, @peter-mouland! I think that does indeed provide a solution for this use-case. I posted a simplified standalone testcase incorporating that fix at https://bugzilla.mozilla.org/attachment.cgi?id=8936087 , which works in all modern browser engines (I tested Firefox, Chrome, Safari, Edge).

**Comment by markofca** [comment] 2017-12-10 02:19
Thanks @peter-mouland and @dholbert.  This seems like a possible work-around and is much appreciated!!  We'll give it a shot to see if we can get our site working in Firefox again.

It's a bit counter-intuitive that this would work given that you're essentially using the selectors of the object to style the clone by passing through intermediate variables styled on the clone root.  In essence we're dodging the boundary rule by sliding in on a custom style on the object.  The clone still needs to access the selectors to know how to draw itself. And if it can do that, it seems like we should be able to use CSS in all its generality.

The workaround is a painful way to work.  Now, for every attribute you might want to style (= number of SVG sub-elements S x number of styled properties P), you need to create a variable in your template.  For all but the most trivial examples, S and P grow very large very quickly.  

It's far easier to specify selectors that cross the boundary  (SVG 1) than trying to manage a flat namespace of everything you might want to modify (SVG 2 with clever workaround).

**Comment by boggydigital** [comment] 2018-06-11 20:10
Not blocking updated 2.0 CR publication - assigning 2.1 WD milestone

**Comment by markofca** [comment] 2019-09-19 08:17
Just saw the recent comments of the SVG Working Group on the thread. 

We launched the site that the issue arose in for us, so figured it might be useful to show the use case and what we were trying to accomplish described above in the thread.  (Also we use SVG very heavily in a pretty aggressive way throughout the site so thought the app might be interesting to the group.)

Desktop link (site works on mobile also, but easier to see the use case from here):
https://www.tango.live/match/main/701/77/20199/-/d/en 

The cheering fan character graphics (and many other elements in the site) are SVG.  The character graphic has about 20 customizable elements (face paint, jersey styles, hair style, colors, etc) and 5 different postures (excited, happy, neutral, sad, despondent).  The graphic in all 5 postures is styled uniquely for each team and for home versus away.

If you click on the vertical nav buttons to the right of the center column (F, 5', 10', 1H, 2H), you can see variations of the character animate into the UI.  If you switch between matches using the top nav, you can see more custom styling for various teams.

We used the work-around suggested and got working implementations in Chrome, Safari, Edge, Firefox, and for a time, IE.  But it's a painful approach.  

Styling the <use>'d element and going the SVG 1.1 approach would have eased development considerably.

**Comment by dirkschulze** [comment] 2019-09-19 23:24
@markofca Thanks a lot for sharing your experience. I wonder if this perception "SVG 1.1 approach would have eased development considerably" will change over time the more people get used to Shadow DOM. Having familiar concepts across the web platform is a strong argument in favour for the SVG 2 changes.

The CSS WG is working on improving the work with Shadow DOM (https://www.w3.org/TR/css-scoping-1/#shadow-dom) as which will have impact on `<use>`.

**Comment by markofca** [comment] 2019-09-20 00:45
@dirkschulze My 2c (which I believe may be sacrilege and apologies in advance)...

As a developer for 30+ years, I personally don't see the Shadow DOM ever being something that a large number of web developers will ever "get". I barely get it myself. 

There feels like a tight coupling between understanding how a browser is implemented and understanding the Shadow DOM.  Not many people understand the former, so I don't have a lot of hope that it will be easy, for example, for people whose day job is styling web pages with CSS to grasp the finer workings of the Shadow DOM. This could just be my own difficulty with it.
 
Partly, I think there is an issue that the terminology for just about everything related to the Shadow DOM (why is it called a shadow DOM even?). It breaks from traditional computer science terminology, and when we're talking about CSS, we have to recognize that even traditional computer science terminology is probably not widely understood.  Developers have common notions of 'class/prototype/template' and 'object/instance', but discussions of shadow DOM introduce a very parallel set of terms for these notions, maybe for good reason, but I'm not so sure.  

In my description above, I see myself casting the discussion back into a more familiar paradigm.  Maybe it would help (or maybe it's too late?) to think about the naming and concepts so that people learning about the Shadow DOM have some meaningful landmarks.  The idea that I instantiate classes into objects and can only style those objects through an interface controlled by the class are readily accessible notions for a first year computer science student.

By contrast, the idea that multiple shadow trees are created with host contexts and distribution lists and shadow-projected content is perplexing.  Quickly reading through the link you provided (which I understand is a spec and not a tutorial) makes me nervous. I would really need to sit down and parse it line by line to try to get the gist of it.

In short, I think the value of CSS is, in part, that it's incredibly accessible to a wide range of people.  I don't see the Shadow DOM as it's currently presented as ever achieving that.  It largely is an implementation detail for browser developers.  In some ways, the encapsulation it's providing seems of limited value compared to the complexity it's introducing.  

The very notion of CSS is somewhat anti-encapsulation (anyone can modify anything anywhere in the DOM) and the shadow DOM, to the extent that it is used widely and not just as something to aid browser development, breaks that paradigm.

I haven't thought about it as much as I'm sure you guys have, but my gut instinct would be preventing/limiting access across the boundary of the shadow DOM is a mistake.  The history of styling shows that early encapsulation (hiding the ability to style scroll bar elements for example) gets undone over time, not the other way around.

I suspect people should be able to style 'instances' freely without limitation.  Yes, that bears the potential for abuse, but on the flip side, everyone will understand it because it reflects how CSS works in the 'normal' case.  Instantiation is useful (replicating structure without replicating code...<use>).  Encapsulation, not so much.

**Comment by dirkschulze** [comment] 2019-09-20 04:21
Thanks @markofca. Let's focus on the behavior of`<use>`. The main developer visible change and the difference between SVG 1.1 and SVG 2 is that elements within the "`<use>`-tree" can not be targeted via CSS directly. @dholbert's workaround seems to be working for you with inconvenience.  Do you see use cases that would no longer work and where there are no workaround?

**Comment by markofca** [comment] 2019-09-20 09:50
@dirkschulze I've now mostly digested this doc: https://www.w3.org/TR/css-scoping-1/#selectors4 and my concerns regarding the ability to cross the boundary of the shadow DOM with CSS in both directions is well addressed through the additional selectors.  If I'm understanding the IRC log, <use> will continue to be an exception to this approach.  Is there some documentation/discussion available that I can read that would help me get up to speed on why that was chosen as the preferred approach?

I believe we're back to this issue above...

"The workaround is a painful way to work. Now, for every attribute you might want to style (= number of SVG sub-elements S x number of styled properties P), you need to create a variable in your template. For all but the most trivial examples, S and P grow very large very quickly."

Essentially, under the SVG 2 approach, <use> becomes prohibitively difficult to use unless a) you are replicating an SVG element with no intention of independently styling the clones or b) you are replicating an SVG object with a trival amount of pre-designed styling built into the structure of the cloned object using the above work-around.

For complex SVG where an illustrator is exporting from Illustrator and where a game or graphic designer is styling this and customizing many aspects of the clones individually, I think the process would become prohibitively complex for all but the most trivial cases.

As a developer I would end up torn between wanting to use the new selectors for styling anything across the shadow DOM boundary and wanting to take advantage of <use> to avoid repeating large amounts of SVG.  The case where you really need <use> is when the cloned object is complex (that is, has many subelements that might need to be styled), and that's precisely where the work-around is prohibitively onerous.

**Comment by dirkschulze** [comment] 2019-09-20 22:58
@tabatkins See https://github.com/w3c/svgwg/issues/367#issuecomment-533488276 Are you aware of additional resources (documentation/issues) for CSS Scoping, Shadow DOM and `<use>`?

**Comment by ThomasBrierley** [comment] 2019-10-04 00:22
Hi :smiley: I've been a silent observer, I think it's time I contributed.

This change affected over 50 products I helped develop, effectively breaking them in FireFox since 2017. Styling 'use' elements based on the _instance-context_ was relied upon as a fundamental building block in such a way that re-writing them was infeasible.

Out of necessity, I've written an "**unpolyfill**" (i think that might be a first? :grin:) to restore partial support for contextual styling of use instance trees (only in the _instance-context_ not the _reference-context_). Perhaps this will provide some quick relief for others affected here too:

https://github.com/ThomasBrierley/svg2use-unpolyfill

@markofca has already passionately argued how this change deprives 'use' of it's most powerful utility (which I could not agree with more). I would instead like to add a couple other concerns which _I think_ are the underlying failures at the center of this issue.

_This is intended to be constructive :) we are all here because we care about SVG_...

#### Implementation vs Utility:

The SVG 1.1 'use' spec for styling required complex implementations, striving for simplification is completely understandable, implementation matters and there is a delicate a balance to strike between simplicity and maintaining a useful level of utility. Unfortunately I don't think these two concerns have been balanced very well here.

On paper the change looks good, on a per-feature basis it appears to retain the majority of the spec _and_ unifies it with another very well developed spec (the shadow DOM). The only problem is those features are not equal. I _suspect_ the prospect of unifying with the shadow DOM proved so attractive that the required omissions were not carefully weighed.

#### Unextensible and Unversioned

SVG 2 does not respect older version declarations. To be honest, this one feels a bit like a [cardinal sin for the w3c](https://www.w3.org/TR/webarch/#ext-version)... perhaps it was assumed this feature was too obscure or poorly supported to matter, I can only contest the latter:

Styling 'use' instance trees based on instance-context was implemented consistently across all major browsers, even IE9 supported it (I know, because I had to support it).

I think if this principle had been respected I probably wouldn't be here, I wouldn't like the change, but it wouldn't have suddenly broken so much content when it landed in FireFox.

...

Perhaps it's too late to address these issues completely, but I do hope restoring styling in the _instance-context_ is carefully considered by the w3c for SVG 2.1 - This behavior makes 'use' worthwhile, without it, it's looks pretty useless, pun intended :wink: thanks for reading if you got this far.

**Comment by ThomasBrierley** [comment] 2019-10-08 00:55
Hi :smiley:

This change affected over 50 products I helped develop, breaking them in FireFox since 2017. Styling 'use' elements based on the _instance-context_ was relied upon as a fundamental building block in such a way that re-writing them was infeasible.

Out of necessity, I've written an "**unpolyfill**" to restore partial support for contextual styling of 'use' instance trees (only in the _instance-context_ not the _reference-context_). Perhaps this will provide some quick relief for others affected by this change:

https://github.com/ThomasBrierley/svg2use-unpolyfill

@markofca has already passionately argued how this change deprives 'use' of it's most powerful utility, which I agree with. I would add: the idea of unifying the spec with the shadow DOM appears to have taken priority over careful weighing of the required omissions _individually_. The 1.1 spec accommodated styling in many possible ways, but the choice was not simply to retain all or none.

However, I wouldn't be here debating this change at all had SVG 2 respected version declarations or required a new declaration like HTML5 to prevent existing content from breaking. Maybe it was assumed this feature was too obscure or poorly supported to qualify as a breaking change... I can only contest the latter: Styling 'use' instance trees based on _instance-context_ was implemented consistently across _all major browsers_, all the way back to IE9 (I know, because I had to support it).

Perhaps it's too late to address versioning, but I hope restoring styling in the _instance-context_ is carefully considered for SVG 2.1 (independently of how well it fits the shadow DOM) - This behavior makes 'use' worthwhile, without it, it's capable of little more than visually identical copies. By only retaining one half of the context based styling implementation is also vastly simplified.

**Comment by theprojectsomething** [comment] 2019-10-23 03:24
Where simply filling a coloured `<symbol>` is an issue (e.g. a logo appearing full colour, fully reversed on e.g. black / white, or partially reversed), this can be resolved by declaring a combo of `color` attributes within the `<symbol>` and then setting `fill: #{flat-color} | currentColor` on the containing `<svg>` (e.g. https://codepen.io/theprojectsomething/pen/eYYvBLK). Combined with css variables this can provide more than the most basic fallback solution.

**Comment by dirkschulze** [comment] 2019-11-08 06:52
@progers @fsoder @rniwa Any comment from WebKit and Blink?

**Comment by george-steel** [comment] 2020-01-16 18:31
Could you give an example of SVG1 use styles depending on instance context. As fair as I can tell, blink styles only according to target context only (for selectors) with instance context only contributing to inherited styles.

**Comment by george-steel** [comment] 2020-01-16 18:47
One of the big benefits of SVG2 scoping is that allows true instance-context dependent styling using ::part() selectors, just like with WebComponents.

**Comment by IanBellomy** [comment] 2020-06-06 18:38
I'm just being bit by this and am dismayed. Imagine if you found out that jpegs will now render differently in different browsers for a while, and your old jpegs may not display the same way moving forward. I'd never go near the format again.

**Comment by longsonr** [comment] 2020-06-06 22:15
@IanBellomy  That's not really how it was/is... Imagine if all jpegs used to display differently. Someone said, wouldn't it be great if they all rendered the same. A new specification for jpegs got rid of some things that made jpegs difficult/impossible to implement. At some point all jpegs render the same but some old ones written a long time ago that always rendered differently now don't render as the author originally intended but then again on many browsers they never did. For jpeg substitute use elements and you have the history.

**Comment by IanBellomy** [comment] 2020-06-06 22:56
@longsonr That's pretty fair. Though it seems that Safari and Chrome reached a consensus at some point, which is not insignificant. I'll zip up until I read some more though.

**Comment by longsonr** [comment] 2020-06-07 06:10
@IanBellomy that's not true either. Chrome a fork of Safari.

**Comment by IanBellomy** [comment] 2020-06-07 14:27
@longsonr Apologies if that behavior indeed stabilized before webkit was forked — in which case it indeed does not indicate that two separate parties came to the same conclusion as I suggested.  

That said, as a developer trying to make things for people my criteria for significance in this instance is the degree to which consistent appearance and behavior can be achieved across systems. Safari is effectively the only browser that runs on iOS and the main browser for macOS users. Chrome is the default browser on Android devices and has large share of users on desktop PC. The fact that Chrome and Safari have a consistent behavior means that I can consistently deliver a consistent experience across many different platforms. That fact is not insignificant. Moreover, if that behavior stabilized before webkit was forked, then the existence of some cross-platform consistency has been the case since ~2013, which itself is notable to me.

**Comment by ThomasBrierley** [comment] 2020-06-07 20:11
> @IanBellomy That's not really how it was/is... Imagine if all jpegs used to display differently. Someone said, wouldn't it be great if they all rendered the same. A new specification for jpegs got rid of some things that made jpegs difficult/impossible to implement. At some point all jpegs will render the same once everyone implements the new specification but a few old ones written a long time ago that always rendered differently now don't render as the author originally intended but then again on many browsers they never did. For jpeg substitute use elements and you have the history.

Sorry this is not quite true either, I think a lot of confusion in this thread stems from the bundling of support for style cascade in the reference-context and instance-context together, when they can be used completely independently. So let me make it clear:

Support for instance-context styling alone was supported by all major browsers since around IE9 (2011). Consistent cross browser support for a feature means it will have been used by devs, it means there is SVG content out there now which is broken.

Where it gets quirky and inconsistent is support for reference-context styling and combining of the cascades. No one is contesting this fact, and it's unlikely anyone utilised it heavily for this reason because cross browser testing will have revealed those quirks.

I am highly suspicious of this decision for nuking both sides of <use> styling support having more to do with the attractiveness of unifying the implementation with the shadow DOM, and so drawing a box around both was convenient if incorrect.

**Comment by IanBellomy** [comment] 2020-06-08 13:50
Thanks @ThomasBrierley.

To clarify, I was personally surprised by the removal of reference styling, e.g. the inclusion of " property values resulting from the CSS cascade", though the issues with instance styling are also surprising. 

In the case a user wanted a kind of template for reuse-with-tweaks, e.g. an enemy space-ship in a game or a person in a crowd, a `symbol` contained in `defs` that can be instanced by `use` seems to fit the occasion perfectly. This approach also mirrors the `template` reuse pattern in html. (I believe this is also how Illustrator exports symbols when exporting SVGs.)

In contrast, achieving this same end by referencing a fragment inside the document where the fragment may or may not be affected by style cascades seems risky (you'll need to be aware of and understand the priorities of any relevant selectors AND how they interact with instance styling rules), _unless the goal was for the instance to appear exactly the way the reference appears in its particular context_.  

Re-presenting an element as it appears effectively provides a kind of render-to-texture result that doesn't otherwise exist in a browser absent complex canvas workarounds. 

This ability also provides a fast way to hack around z-index limitations in some cases, especially when re-organizing a complex document tree to achieve proper z-order would effect the appearance of the elements. [Aside: Is z-index still in SVG2 even?]

It seems this result is not possible to achieve at all in SVG2. Absent a way to control for version,  there's no way implement alternative CSS or JS to get cross platform consistency. So this feature is dead even though SVG2 support is minimal.  

It seems it's only my recollection though that, at least a few years ago, _mixing_ styles was what was flaky — that reference and instance styling could be used somewhat reliably if relatively _independently_.... (I've had minimal contact with SVG before maybe 2015 though — I stuck to Flash as long as possible in no small part to avoid this kind of thing.)

**Comment by ThomasBrierley** [comment] 2020-06-09 00:00
> I was personally surprised by the removal of reference styling, i.e. the use of the fragment's context to determine what it'd look like [...] In the case a user wanted a kind of template for reuse-with-tweaks

As a quick and easy tweak I can see how this might be missed, I was thinking more in terms of what is possible in absolutes... Reference context dependence can be avoided with some re-thinking of CSS. However utilizing context-based styling is very powerful because you can make things automatically look entirely (or slightly) different, with minimal CSS - or at least you could, but now it would require much duplication with the same CSS, not merely re-arranging it.

> It seems it's only my recollection though that, at least a few years ago, mixing styles was what was flaky — that reference and instance styling could be used somewhat reliably if relatively independently

You may be correct for more recent years, I remember needing to avoid it for older browsers originally though. Relying on the merging of those cascades is definitely the inconsistent part though.

> This kind of exact re-presentation does not seem possible to achieve at all in SVG2. Absent a way to control for version, there's no way implement alternative CSS or JS to get cross platform consistency either. So this feature is presently dead even though SVG2 support is minimal. At least instance styling can be achieved, albeit with a new high-friction approach (though it is still breaking of course).

In case you missed it, I wrote an unpollyfill (i.e a pollyfill for SVG v1) that restores instance-context styling:

https://github.com/ThomasBrierley/svg2use-unpolyfill

I wrote this with care to be as performant and minimal as possible, it is well tested and in use throughout all of the products I help develop (in fact i've skipped adding it to application development and injected this straight into index pages server side inside of a condition for firefox useragents).

However I skipped the reference context styling because of the extra complexity and performance penalties it would incur. It would be quite possible to extend this pollyfill with that support, though keeping it dynamic AND performant may be challenging... using `Element.currentStyle` would be the inroad to that support, although that is non-standard, but supported by FireFox which is the only place this issue currently exists (I do wonder sometimes if it will ever go beyond FireFox, it's been 4 years now).

**Comment by IanBellomy** [comment] 2020-06-09 01:30
> Reference context dependence can be avoided with some re-thinking of CSS. However utilizing context-based styling is very powerful because you can make things automatically look entirely (or slightly) different, with minimal CSS - or at least you could, but now it would require much duplication with the same CSS, not merely re-arranging it.

Indeed. When I said that it's impossible that was not quite right — but the absence of reference styling does / could mean significant refactoring, the need to remember the constraints the document needs to follow at some point in the future, and more JS to manage complex trees.  

> using Element.currentStyle would be the inroad to that support

This is an interesting idea I hadn't thought of! Though in addition to potential overhead, that overhead would grow over time from just a few users to every user as more agents implemented SVG2...

**Comment by ThomasBrierley** [comment] 2020-06-09 13:49
> in addition to potential overhead, that overhead would grow over time from some users to every user as more agents implemented SVG2.

Yes, it's far from ideal, the mutation observers add non-insignificant overhead, it's usable but makes `use` more expensive.

I wrote the polyfill out of necessity for compatibility rather than a way forward... the sheer number of assets we had utilizing SVG USE were too great to wrangle into the 'new' awkward way of achieving context base styling within the shadow DOM (see higher in this thread).

This is the _other_ problem with this issue: backwards incompatible changes in what is supposed to be a backwards compatible revision...

**Closed** 2023-06-27 11:02 UTC
Labels: Document structure chapter, Needs WG input, Use Element
