### ISSUE TITLE
SVGAElement all attributes except href should be as HTML i.e. not SVGAnimatedString

### ISSUE THREAD

**Issue by longsonr** [w3c/svgwg#315] opened 2017-05-07 15:08 UTC
download, rel, relList, hreflang and type are all modelled as SVGAnimatedString attributes. There seems no reason to do this as they aren't much use as things to be SMIL animated (in fact download is stated to be non-animatable in the spec).

  Possible solution

    have these the same as the HTML specification i.e. 

           [SetterThrows]
           attribute DOMString download;
           [SetterThrows]
           attribute DOMString rel;
           [PutForwards=value]
           readonly attribute DOMTokenList relList;
           [SetterThrows]
           attribute DOMString hreflang;
           [SetterThrows]
           attribute DOMString type;

**Comment by AmeliaBR** [comment] 2017-05-07 15:10
Closing as duplicate of #312. @longsonr, could you please add your suggestions to that issue?

**Comment by AmeliaBR** [comment] 2017-05-07 15:13
Hmm... unless you want to make this a separate issue, just for the second point.  In which case, edit the title accordingly & I'll re-open.

For reference: I made them animated strings for consistency with the SVG 1.1 properties on the interface.  But I agree that there's no real use for them.

**Comment by longsonr** [comment] 2017-05-07 15:16
Let's make it a separate issue.

**Comment by longsonr** [comment] 2017-05-07 15:24
@AmeliaBR I've narrowed it to just the non-href attributes. Can you reopen it please?

**Comment by dstorey** [comment] 2018-03-12 10:11
I agree this is a good idea, especially as they're not currently implemented (AFAICT) with the exception of download in Firefox, but [they implemented it as DOMString anyway](https://dxr.mozilla.org/mozilla-central/source/dom/webidl/SVGAElement.webidl).

We could even possibly look to pull them in from HTML as part of a mixin if they matched, which would keep them in sync.

**Comment by liamquin** [comment] 2018-03-19 19:28
@longsonr , can Mozilla contribute any tests in this area to wpt for svg, assuming we change them to DOMString?

**Comment by liamquin** [comment] 2018-03-19 19:34
[either way, we need to mark Dom support for these attributes as at risk in SVG unless we know we're getting 2 implementations this Summer.]

**Comment by dstorey** [comment] 2018-03-19 20:30
I agree with @dirkschulze about avoiding any new SVGAnimatedString.  We (Edge) are unlikely to implement these in the current form. Sharing the definition/implementation with HTML would make it more likely that we would implement.

**Comment by dstorey** [comment] 2018-03-20 05:08
There are presumably 3 implementers (@dirkschulze, @longsonr, myself) in favour of using the HTML definition rater than SVGAnimatedString. 

@liamquin, @AmeliaBR, @boggydigital: can we get a resolution on the change here, or do we need to do that formally on a call? 

Furthermore do we want to do the same as tabIndex/dataset et al and ask HTML to define the common ones in a mixin that we include?

**Comment by liamquin** [comment] 2018-03-20 05:52
A related issue is that href has to remain an SVFAnimatedString. So anythink defined by HTML wouldn't include that. Another is that we need at least a couple of tests. Maybe I'll look at writing one for each attribute, if we agree on a type.

Yes, we need a minuted decision for spec changes, because we're at Candidate Rec, and this one is substantive (although sensible).

I've added Agenda+ as a label to put this on next week's agenda

**Comment by dstorey** [comment] 2018-03-20 06:02
Presumably target has to remain as that is implemented as specced, unless the usage is low enough we can change that one. Google has a measure on that one: https://www.chromestatus.com/metrics/feature/popularity#V8SVGAElement_Target_AttributeGetter

**Comment by dstorey** [comment] 2018-03-20 06:15
We should probably adapt the HTML tests for SVG here.
Download (presumably should pass in Firefox) and rel are at https://wpt.fyi/html/semantics/text-level-semantics/the-a-element

There are some rellist tests at https://w3c-test.org/html/semantics/rellist-feature-detection.html

**Comment by boggydigital** [comment] 2018-06-11 19:35
Not blocking updated 2.0 CR publication - assigning 2.0 Recommendation. We would want to fix this before publishing 2.0 Recommendation, but it's not urgent for updated CR

**Comment by AmeliaBR** [comment] 2018-08-13 23:59
Closing this issue after the changes merged in #409.

Those changes make the spec consistent with the Firefox implementation for all properties defined directly on the `SVGAElement` interface, and make it consistent with HTML for everything except `href` and `target`.

See #526 for further discussion of `target`.

See #312 for further discussion of `href` and the `HTMLHyperlinkUtils` mixin properties.

**Closed by AmeliaBR** 2018-08-13 23:59 UTC
Labels: HTML Consistency, Linking chapter, SVG Core
